upstream go_backend {
    server 127.0.0.1:8081;
}

upstream python_static {
    server 127.0.0.1:8082;
}

server {
    listen 8080;

    # 1. 精确匹配：只要是访问 /dashboard 或 /api，就去投奔 Go
    location /dashboard {
        proxy_pass http://go_backend;
    }

    location /api {
        proxy_pass http://go_backend;
    }

    # 2. 兜底匹配：其他的（根路径 / 等）全部去 Python 
    location / {
        proxy_pass http://python_static;
    }
}
